name = "cf-workers-telegram-bot-v2"
main = "packages/worker/src/worker.ts"

workers_dev = true
compatibility_date = "2024-05-13"
node_compat = true
compatibility_flags = [ "nodejs_compat" ]

build.command = "npm install && npm run build:worker"
